### PR TITLE
Update to Swift 5.8

### PR DESCRIPTION
**Pull request by finestructure**
Partially addresses #16

### CODE REVIEW

**Comment by finestructure** [comment]
Hi @MarcoEidinger , any chance you could give this a quick look and merge? It should be all that's needed to get us into working order again :)

**Comment by MarcoEidinger** [comment]
Hi @finestructure, thanks for the PR! Should work. I’ll merge and you can integrate and test. Once you confirm I’ll create 2.4 release

**Comment by MarcoEidinger** [comment]
@finestructure there is an issue with https://github.com/SwiftPackageIndex/ReleaseNotes when building with Swift 5.8

```
  Building for production...
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
  [1/3] Compiling SemanticVersion NSRegularExpression+ext.swift
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
  [3/5] Compiling ArgumentParserToolInfo ToolInfo.swift
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
  [5/7] Compiling Parsing OneOfBuilder.swift
  [7/8] Compiling ArgumentParser BashCompletionsGenerator.swift
  remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
  [9/10] Compiling ReleaseNotesCore App.swift
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:22:9: error: ambiguous use of 'parser(of:radix:)'
          Int.parser()
          ^
  /_swift-release-notes/.build/checkouts/swift-parsing/Sources/Parsing/Parsers/Int.swift:37:22: note: found this candidate
    public static func parser(
                       ^
  /_swift-release-notes/.build/checkouts/swift-parsing/Sources/Parsing/Parsers/Int.swift:59:22: note: found this candidate
    public static func parser(
                       ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:34:9: error: ambiguous use of 'parser(of:radix:)'
          Int.parser()
          ^
  /_swift-release-notes/.build/checkouts/swift-parsing/Sources/Parsing/Parsers/Int.swift:37:22: note: found this candidate
    public static func parser(
                       ^
  /_swift-release-notes/.build/checkouts/swift-parsing/Sources/Parsing/Parsers/Int.swift:59:22: note: found this candidate
    public static func parser(
                       ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:53:18: error: ambiguous use of 'init(_:)'
              .map(String.init)
                   ^
  Swift.String:2:23: note: found this candidate
      @inlinable public init(_ substring: __shared Substring)
                        ^
  Swift.String:2:12: note: found this candidate
      public init(_ content: Substring.UnicodeScalarView)
             ^
  Foundation.String:3:12: note: found this candidate
      public init(_ attrStrSlice: Slice<AttributedString.CharacterView>)
             ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:68:34: error: ambiguous use of 'init(_:)'
          Prefix { $0 != " " }.map(String.init)
                                   ^
  Swift.String:2:23: note: found this candidate
      @inlinable public init(_ substring: __shared Substring)
                        ^
  Swift.String:2:12: note: found this candidate
      public init(_ content: Substring.UnicodeScalarView)
             ^
  Foundation.String:3:12: note: found this candidate
      public init(_ attrStrSlice: Slice<AttributedString.CharacterView>)
             ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:79:34: error: ambiguous use of 'init(_:)'
          Prefix { $0 != " " }.map(String.init)
                                   ^
  Swift.String:2:23: note: found this candidate
      @inlinable public init(_ substring: __shared Substring)
                        ^
  Swift.String:2:12: note: found this candidate
      public init(_ content: Substring.UnicodeScalarView)
             ^
  Foundation.String:3:12: note: found this candidate
      public init(_ attrStrSlice: Slice<AttributedString.CharacterView>)
             ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:95:41: error: unable to infer type of a closure parameter 'count' in the current context
      static let packageUpdate = Parse { (count, updates) -> [Update] in
                                          ^
  /_swift-release-notes/Sources/ReleaseNotesCore/Parser.swift:95:48: error: unable to infer type of a closure parameter 'updates' in the current context
      static let packageUpdate = Parse { (count, updates) -> [Update] in
                                                 ^
  make: *** [Makefile:35: swift-release-notes] Error 1
  The command '/bin/sh -c git clone -b  $SWIFT_RELEASENOTES_BRANCH $SWIFT_RELEASENOTES_REPOSITORY _swift-release-notes     && cd _swift-release-notes     && git checkout main     && apt-get update     && apt-get install make     && make install     && cd' returned a non-zero code: 2
```
Screenshot 2023-05-01 at 11 23 25 AM

Can you provide a fix for the tool so that this GitHub action will work when using Swift 5.8 ?

**Comment by finestructure** [comment]
Oh right, there were some breaking changes with swift-parsing and 5.8. I'll sort that out asap!

**Comment by finestructure** [comment]
I've fixed this in [version 0.1.0](https://github.com/SwiftPackageIndex/ReleaseNotes/releases/tag/0.1.0)!

**Comment by MarcoEidinger** [comment]
Thanks, my testing confirmed that with your PR here and Release Notes version 0.1.0 the workflow works fine

```yml
  dependencies:
    uses: MarcoEidinger/swift-package-dependencies-check/.github/workflows/reusableWorkflow.yml@859eb086d58d5683a5cb7302be38db8b4cf0a112
    with:
      commit-message: 'Package update'
``` 

I will try to address the remaining issue in #16 (action did not fail despite there was an error) before I create 2.4 release and point to that in v2 tag

**Pull request merged**
